import "./globals.css";
import { Typography } from "@mui/material";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='starry-sky'>
        <h1>Star Wars Starships</h1>

        {children}
      </body>
    </html>
  );
}
